# Generated by Django 4.2.6 on 2024-02-15 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="test",
        ),
    ]
