# Generated by Django 4.2.6 on 2024-02-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="github_token",
            new_name="default_external_repository_token",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="default_github_host",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="default_github_username",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_external_repository_host",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Default Expernal Repository Host",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_external_repository_username",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Default GitHub Username",
            ),
        ),
    ]
