# Generated by Django 4.2.6 on 2024-02-20 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "app",
            "0002_rename_github_token_userprofile_default_external_repository_token_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={"ordering": ["user__last_name"]},
        ),
        migrations.RemoveField(
            model_name="project",
            name="external_repo_url",
        ),
        migrations.AddField(
            model_name="project",
            name="external_repository_url",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="External repository URL",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="access",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("members", "Members"),
                    ("private", "Private"),
                ],
                default="public",
                max_length=10,
                verbose_name="View access",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="build_output",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="Build output"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Project description",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_built",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last built"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_modified",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last modified"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="member",
            field=models.ManyToManyField(
                blank=True,
                related_name="member_many_to_many",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Member",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Project name"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="user_interaction",
            field=models.ManyToManyField(
                blank=True,
                related_name="last_updated_by_user_many_to_many",
                through="app.UserProjectAttribute",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User interaction",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="default_external_repository_token",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Default External Repository Token",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
