# Generated by Django 4.2.6 on 2024-01-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_project_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
            ),
        ),
    ]
