# Generated by Django 4.2.6 on 2024-01-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprojectattribute",
            name="repo_password_token",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="userprojectattribute",
            name="repo_username",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
