# Generated by Django 4.2.6 on 2024-02-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_project_access"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                check=models.Q(("access__in", ["PR", "ME", "PU"])),
                name="app_project_access_valid",
            ),
        ),
    ]
