# Generated by Django 4.2.6 on 2024-02-20 19:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_project_app_project_access_valid"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="project",
            name="app_project_access_valid",
        ),
    ]
