# Generated by Django 4.2.6 on 2024-01-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_remove_project_external_repo_password_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="last_built",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="last_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
