# Generated by Django 4.2.6 on 2024-02-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_remove_project_app_project_access_valid"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                check=models.Q(("access__in", ["PR", "ME", "PU"])),
                name="app_project_access_valid",
            ),
        ),
    ]
