# Generated by Django 4.2.6 on 2024-02-21 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_project_app_project_access_valid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="user_interaction",
        ),
    ]
