# Generated by Django 4.2.6 on 2024-02-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_project_build_output"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_hash",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
