# Generated by Django 4.2.6 on 2024-02-04 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_project_project_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="project_hash",
        ),
    ]
