# Generated by Django 4.2.6 on 2024-02-21 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0008_remove_project_user_interaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprojectattribute",
            name="repo_username",
        ),
        migrations.AddField(
            model_name="userprojectattribute",
            name="repository_username",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Respository username",
            ),
        ),
        migrations.AlterField(
            model_name="userprojectattribute",
            name="last_accessed",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Last accessed"
            ),
        ),
        migrations.AlterField(
            model_name="userprojectattribute",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.project",
                verbose_name="Project",
            ),
        ),
        migrations.AlterField(
            model_name="userprojectattribute",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
