# Generated by Django 4.2.6 on 2024-02-21 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_remove_userprojectattribute_repo_username_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprojectattribute",
            old_name="repo_password_token",
            new_name="repository_password_token",
        ),
    ]
