# Generated by Django 4.2.6 on 2024-02-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_remove_project_project_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="access",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("members", "Members"),
                    ("public", "Public"),
                ],
                default="private",
                max_length=10,
            ),
        ),
    ]
