# Generated by Django 4.2.6 on 2024-02-21 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "app",
            "0010_rename_repo_password_token_userprojectattribute_repository_password_token",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectgroup",
            name="member",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="Member"
            ),
        ),
        migrations.AlterField(
            model_name="projectgroup",
            name="name",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="projectgroup",
            name="project_access",
            field=models.ManyToManyField(
                blank=True,
                to="app.project",
                verbose_name="Projects with access to",
            ),
        ),
        migrations.AlterField(
            model_name="userprojectattribute",
            name="repository_password_token",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Respository password or token",
            ),
        ),
    ]
