# Generated by Django 4.2.6 on 2024-02-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_alter_project_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="access",
            field=models.CharField(
                choices=[
                    ("public", "Public2"),
                    ("members", "Members2"),
                    ("private", "Private2"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]
