# Generated by Django 4.2.6 on 2024-02-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app",
            "0011_alter_projectgroup_member_alter_projectgroup_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectgroup",
            name="project_access",
            field=models.ManyToManyField(
                blank=True,
                to="app.project",
                verbose_name="Project(s) with access to",
            ),
        ),
    ]
