# Generated by Django 4.2.6 on 2024-02-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_alter_project_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="access",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("members", "Members"),
                    ("private", "Private"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]
