#TODO: need to pin down ubuntu version
FROM ubuntu:latest 
WORKDIR /dcsp

#TODO: may need to remove update as this will have different updates over time
#TODO: do we need upgrade as well for security?
RUN apt-get update
COPY packages.txt /dcsp
RUN xargs apt-get -y install <packages.txt

COPY requirements.txt /dcsp
RUN pip install -r requirements.txt

# Chown all the files to user.
ARG UNAME=dcspuser
RUN groupadd $UNAME
RUN useradd $UNAME
RUN chown -R $UNAME /dcsp
RUN chmod -R g+rw /dcsp
USER $UNAME

